### ISSUE TITLE
[Feature] Commands in datapacks

### ISSUE THREAD

**Issue by Vervixer** [Keksuccino/Biomes-in-Jars#1]
When using the command setchunkbiome in functions (As in datapacks), the log displays "com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here".

If it were possible to use it in code, then many interesting scenarios - like corrupting the world Terraria-style - become available.

**Comment by Keksuccino** [comment]
Hi! I would need to add coordinate arguments then. Is this okay for datapacks?

**Comment by Vervixer** [comment]
I think so. But even without arguments it should work I guess, because if you'll take coordinates of the "summoner" of the command then you can easily change that with `execute at @s positioned ~ ~10 ~ run setchunkbiome test:test` for example.

**Comment by Keksuccino** [comment]
Mod got updated! The command now accepts coordinates! :) Thank you for your suggestion!
