### ISSUE TITLE
Note to Author - This is the coolest mod I have seen in a long time!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Keksuccino/Biomes-in-Jars#2]
This is unbelievably creative. I am really impressed you decided to make this like it honestly blows me away. This solves the problem of having to RTP when someone claims the biome you want because you can make your biome your way I cannot wait to use this - thank you so much for your hard work. I will be giving you a special thanks in my modpack since this is the most original idea since Thaumcraft!

**Comment by Keksuccino** [comment]
Aw, thank you so much! ^-^
