### ISSUE TITLE
[1.18.2] Crash on startup, Mod incompatibility

### ISSUE THREAD

**Issue by ConqAra** [Keksuccino/Biomes-in-Jars#5]
I have a lot of mods on so it's probably a mod incompatibility

Log: [https://paste.ee/p/KkCkM](https://paste.ee/p/KkCkM)

**Comment by Keksuccino** [comment]
Log does not exist anymore, so I can't debug this, sorry.
It's also possible that it already got fixed.
If it still happens when using the latest Biomes In Jars build, please open a new issue, thank you very much!
